name: CI CD Pipeline

on:
  push:
    branches:
      - dev
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install bleach
        run: pip install bleach
      - name: Execute tests
        env:
          DJANGO_SETTINGS_MODULE: LittleLemon.settings

        run: python3 manage.py test LittleLemonApi.tests.smoke_tests
